remote_theme: ISSAE/architect

name: Programmation Avancée ED5

author: Pascal Fares

author_email: pascal.fares@isae.edu.lb

title: Par l'exemple. Composite, Factory, Visitor, Interprete, Builder, Template
description: Programmation Avancée et Patron de conception en Java

google_analytics: UA-29708002-2

repository: ISSAE/nfp121.ed5

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

